# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

# colorScheme = "slate"
colorScheme = "Avocado"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]
# robots = ""

[header]
  layout = "fixed" # valid options: basic, fixed

[announcement]
  enable = false
  id = "global"
  # Set `content` to markdown text or `contentInline` to raw HTML for the banner message.
  content = ""
  dismissible = true
  showOnce = true
  style = "info" # valid options: info, accent, warning, success, danger
  showOnPages = []
  hideOnPages = []

[footer]
  showMenu = false
  showCopyright = false
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile" # valid options: page, profile, hero, card, background, custom
  #homepageImage = "IMAGE.jpg" # used in: hero, and card
  showRecent = false
  showRecentItems = 5
  showMoreLink = false
  # showMoreLinkDest = "/posts"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = false # only used when layout equals background

[article]
  showDate = true
  #showViews = true
  #showLikes = true
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "basic" # valid options: basic, big, background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = false 
  showAuthorsBadges = false 
  showWordCount = true
  showSummary = true
  sharingLinks = [ "linkedin", "twitter", "whatsapp", "pinterest", "reddit", "facebook", "email"]

[list]
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = true

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true

[firebase]
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
